/*----------------------------------------------------------------------------*/
/*
  This file is generated by code_saturne, a general-purpose CFD tool.
*/
/*----------------------------------------------------------------------------*/

#include "cs_defs.h"

/*----------------------------------------------------------------------------
 * Standard C library headers
 *----------------------------------------------------------------------------*/

#include <assert.h>
#include <math.h>

#if defined(HAVE_MPI)
#include <mpi.h>
#endif

/*----------------------------------------------------------------------------
 *  Local headers
 *----------------------------------------------------------------------------*/

#include "cs_headers.h"

/*----------------------------------------------------------------------------*/

BEGIN_C_DECLS

/*----------------------------------------------------------------------------*/

cs_real_t *
cs_meg_boundary_function(const char       *zone_name,
                         const cs_lnum_t   n_elts,
                         const cs_lnum_t  *elt_ids,
                         const cs_real_t   xyz[][3],
                         const char       *field_name,
                         const char       *condition)
{
  cs_real_t *new_vals = NULL;

  /* User defined formula for "turbulence_spalart" over BC=inlet
    ------------------------------------------------------------ */

  if (strcmp(field_name, "turbulence_spalart") == 0 &&
      strcmp(condition, "formula") == 0 &&
      strcmp(zone_name, "inlet") == 0) {

    const cs_lnum_t vals_size = n_elts * 1;
    BFT_MALLOC(new_vals, vals_size, cs_real_t);

    const cs_real_t turbIntensity = cs_notebook_parameter_value_by_name("turbIntensity");
    const cs_real_t vel_inf = cs_notebook_parameter_value_by_name("vel_inf");

    cs_real_t cmu = -1.;
    cs_real_t I = -1.;
    cs_real_t dh = -1.;
    cs_real_t l = -1.;
    cs_real_t k = -1.;
    cs_real_t eps = -1.;
    for (cs_lnum_t e_id = 0; e_id < n_elts; e_id++) {
      cs_lnum_t b_e_id = elt_ids[e_id];
      cmu = 0.09;
      I = turbIntensity;
      // Diametro hidraulico
      //dh=2.510117647;
      // Longitud del GTS
      dh = 2.47648095;
      // Turbulent length scale (l)
      l = 0.07 * dh;
      k = 1.5 * cs_math_pow2((I * vel_inf));
      eps = cmu * (pow(k, 1.5)) / l;
      new_vals[0 * n_elts + e_id] = (cmu * k) / eps;
    }
  }
  return new_vals;
}

/*----------------------------------------------------------------------------*/

END_C_DECLS

