/*----------------------------------------------------------------------------*/
/*
  This file is generated by code_saturne, a general-purpose CFD tool.
*/
/*----------------------------------------------------------------------------*/

#include "cs_defs.h"

/*----------------------------------------------------------------------------
 * Standard C library headers
 *----------------------------------------------------------------------------*/

#include <assert.h>
#include <math.h>

#if defined(HAVE_MPI)
#include <mpi.h>
#endif

/*----------------------------------------------------------------------------
 *  Local headers
 *----------------------------------------------------------------------------*/

#include "cs_headers.h"

/*----------------------------------------------------------------------------*/

BEGIN_C_DECLS

/*----------------------------------------------------------------------------*/

void
cs_meg_volume_function(const char      *zone_name,
                       const cs_lnum_t  n_elts,
                       const cs_lnum_t *elt_ids,
                       const cs_real_t  xyz[][3],
                       cs_field_t       *f[])
{
  /* User defined formula for variable(s) density over zone all_cells
    ----------------------------------------------------------------- */

  if (strcmp(f[0]->name, "density") == 0 &&
      strcmp(zone_name, "all_cells") == 0) {
    const cs_real_t rho0 = cs_glob_fluid_properties->ro0;

    for (cs_lnum_t e_id = 0; e_id < n_elts; e_id++) {
      cs_lnum_t c_id = elt_ids[e_id];
      f[0]->val[c_id] = rho0;
    }
  }

  /* User defined formula for variable(s) molecular_viscosity over zone all_cells
    ----------------------------------------------------------------------------- */

  if (strcmp(f[0]->name, "molecular_viscosity") == 0 &&
      strcmp(zone_name, "all_cells") == 0) {
    const cs_real_t mu0 = cs_glob_fluid_properties->viscl0;

    for (cs_lnum_t e_id = 0; e_id < n_elts; e_id++) {
      cs_lnum_t c_id = elt_ids[e_id];
      f[0]->val[c_id] = mu0;
    }
  }
}

/*----------------------------------------------------------------------------*/

END_C_DECLS

